### ISSUE TITLE
[System Architecture] 디자인

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/travel-board#21]
**[Context]**

1. Route53 with ACM, Application Load Balancer, ECS, ECR 학습

2. 학습 후에, System Architecture 디자인

3. 디자인 Diagram 그려서, 공유

**Comment by Biotea92** [comment]
[이론 학습 내용](https://github.com/Biotea92/2024-flab-study/blob/master/12.%20AWS.md)

**Comment by Biotea92** [comment]
[디자인 Diagram](https://github.com/f-lab-edu/travel-board/wiki/%F0%9F%93%A2-System-Architecture)
