### ISSUE TITLE
[CI 설정]

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/travel-board#34]
**[Context]**

1. Dockerfile

- admin, user > dockerfile 

2. Github Action

- CI  
- Test code 가 성공 ( unit, e2e )
- gradle build 자체 성공 확인
- dockerizing 

3. CD ( TBD )

4. 다른 CI, CD 툴 학습 및 비교 (Jenkins 제외)

**Comment by Biotea92** [comment]
# CI CD tool 비교 

| 특징        | Jenkins                                 | GitLab CI                               | Circle CI                              | Travis CI                                   | GitHub Actions                                               | 
|-----------|-----------------------------------------|-----------------------------------------|----------------------------------------|---------------------------------------------|--------------------------------------------------------------|
| 오픈소스      | O                                       | O                                       | X                                      | O                                           | X                                                            |
| VCS 통합    | git, subversion, Mercurials 등 플러그인으로 지원 | GitLab과 통합                              | GitHub등 지원                             | Github과 통합                                  | Github repository와 통합                                        |
| 자동화 기능    | 높은 수준의 자동화 가능, 수동설정 필요                  | GitLab내에서 제공하는 내장 자동화 도구 제공             | Docker를 사용하는 프로젝트에 특히 강력한 자동화 CI/CD 지원 | 오픈 소스 프로젝트에 중점을 둔 자동화 CI/CD 지원              | GitHub에 통합된 빠른 자동화                                           |
| 커스터 마이징   | 다양한 플러그인을 통한 커스터마이징 기능            | 통합 및 API를 통한 커스터마이징 가능, 외부 플러그인 의존도가 낮음 | 클라우드 기반 기술 중점에서는 커스터마이징 가능             | 빌드 매트릭스 기능을 통한 커스터마이징 옵션 제공                 | Github 환경 내에서 워크플로우 커스터마이징 가능                                | 
| 보안 기능     | 보안 플러그인 제공, 수동 설정 필요                    | 통합된 플랫폼으로 기본 보안 기능 제공                   | 통합된 도구와 구성을 통해 보안 제공                   | 설정에 따라 다양한 보안 통합 기능 제공                      | API 키와 같은 민감한 데이터를 처리하기 위한 방법 제공                             | 
| 성능 및 속도   | 분산 빌드를 지원                               | Git 기반 프로젝트에 대해 효율적인 성능 제공              | 클라우드 기반 병렬 처리로 빠른 성능 제공                | 빌드 및 테스트 프로세스에서 효율적 성능 제공                   | repository와 밀접한 통합 덕분에 빠른 워크플로우 실행 가능                        |
| 커뮤니티 및 지원 | 큰 커뮤니티와 광범위한 문서를 제공하여 지원 용이             | GitLab 커뮤니티와 지원을 통한 지원 제공               | 개발자 경험이 용이, 협업 지식 교환 활발                | 오픈 소스 프로젝트에서 커뮤니티 지원 제공                     | Github의 광범위한 커뮤니티 직관적인 설정 제공                                 | 
| 비용 및 라이센스 | 오픈소스로 무료이나 인프라 비용이 발생                   | 무료 및 유료 플랜이 존재, 플랜에 따라 기능이 달라짐          | 무료 및 유료 플랜이 존재, 고급 기능은 유표 플랜에서 제공      | 오픈 소스 프로젝트에는 무료로 제공되며, 프라이빗 프로젝트에는 유료 플랜 제공 | public repository에 대해 무료로 제공, private repository는 사용량에 따라 과금 |
