### ISSUE TITLE
[ERD] 생성

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/travel-board#4]
**[Context]**

- AWS EC2 > 직접 MYSQL 설치 
- Localhost 에서 EC2 안에 존재하는 MYSQL 에 접근이 가능해야한다.
- 그 이후에, 해당 MYSQL 에 설계한 ERD table 생성

**Comment by Biotea92** [comment]
AWS에 EC2 인스턴스 두개를 생성하고, ERD 생성했습니다. 

- VPC는 AWS에서 기본으로 제공하는 구성을 그대로 사용했습니다.
- 두 인스턴스를 같은 subnet에 위치 시켰습니다. 
- WAS를 띄울 인스턴스에서 MYSQL에 private IP로 접속하고 ERD table 생성했습니다.
