### ISSUE TITLE
[SpringBoot] 프로젝트 폴더 구성 (구조) 옵션 만들기

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/travel-board#5]
**[Context]**
1. 예시 > Controller/Service/Repositor...... [v]
2. 예시 > Web/Service/Repo...
3. 예시 > adapter/....

**[Acceptance]**
- 여러가지 프로젝트 폴더 구조를 학습, 고민 후 Option 을 만들어서 해당 Issue 코멘트에 정리

**[Note]**
- Multi-module 프로젝트로 구성을 할 예정. 때문에, 이 부분을 고민해보기
-  다음과 같은 멀티 모듈을 만들 예정 입니다.
`
storage / api-user / api-admin / support
`

**Comment by Biotea92** [comment]
프로젝트의 패키지 구조는 대표적으로 Package by Layer 와 Package by Feature, Hexagonal architecture가 있습니다. 

## Package by Layer

- 프로젝트의 계층별로 패키지를 구성하는 방식 
- 패키지에 서로 밀접하게 관련되지 않은 클래스가 포함되어 있기 때문에 패키지내 응집력(Cohesion)이 감소된다
- `Repository`는 `Service`에서 사용되고, `Service`는 `Controller`에서 사용될 것이므로 패키지들간 높은 결합이 생긴다. 

> Cohesion :   
> 패키지 멤버 간의 논리적 관련성을 의미한다.  
> 높은 응집력은 패키지의 독립성을 보장하고, 낮은 응집력은 독립성을 감소 시키고 재사용성과 이해도를 감소시킨다. 
> 
> Coupling :  
> 패키지들 간의 상호 의존성 정도를 의미한다.
> 낮은 결합은 유지보수성을 향상시킨다. 
> 
>> 좋은 시스템 설계를 위해서는 패키지 내 높은 응집력(Cohesion)과 패키지간 낮은 결합도(Coupling)가 필수적이다. 

```
├── com.app
    └── controller
        ├── PostController
        ├── ProductController
        └── UserController
    └── model
        ├── Post   
        ├── Product
        └── User
    └── repository
        ├── PostRepository   
        ├── ProductRepository
        └── UserRepository
    └── service
        ├── PostService
        ├── ProductService
        └── UserService
    └── util
```

## Package by Feature

- 프로젝트의 기능별로 패키지를 구성하는 방식
- 패키지에는 서로 관련된 클래스만 포함되어 있기 때문에 패키지내 응집력이 높아진다.
- 다른 패키지의 클래스에서 클래스를 사용하는 것이 제거되기 때문에 결합도가 낮아진다. 

```
├── com.app
    └── post
        ├── Post
        ├── PostController
        ├── PostRepository        
        └── PostService
    └── product
        ├── Product   
        ├── ProductController
        ├── ProductRepository
        └── ProductService
    └── util
    └── user
        ├── User   
        ├── UserController
        ├── UserRepository
        └── UserService
```

## Hexagonal Architecture
포트와 어댑터 아키텍처로도 알려져 있다. 

### 주요 개념

#### 도메인 (Domain)
시스템의 핵심 비즈니스 로직과 규칙을 포함하는 부분입니다. 이 계층은 외부 기술에 독립적이어야 하며, 오직 도메인 로직에만 집중한다.

#### 포트 (Ports)
도메인 계층이 외부와 상호작용하기 위해 사용하는 인터페이스이다. 포트는 입력 포트(도메인으로 들어오는 요청)와 출력 포트(도메인에서 나가는 요청)로 나눌 수 있다.

#### 어댑터 (Adapters)
포트를 구현하여 외부 시스템과 도메인 계층을 연결하는 역할을 한다.  
어댑터는 입력 어댑터(예: REST 컨트롤러, 메시지 리스너)와 출력 어댑터(예: 데이터베이스 리포지토리, 외부 API 클라이언트)로 나눌 수 있다.

```
com.example.project
 ├── application
 │    ├── ports
 │    │    ├── input
 │    │    │    └── UserService.java
 │    │    └── output
 │    │         └── UserRepository.java
 │    └── services
 │         └── UserServiceImpl.java
 ├── domain
 │    ├── model
 │    │    └── User.java
 │    └── exceptions
 │         └── UserNotFoundException.java
 ├── adapters
 │    ├── input
 │    │    └── rest
 │    │         └── UserController.java
 │    └── output
 │         └── persistence
 │              ├── UserEntity.java
 │              ├── SpringDataUserRepository.java
 │              └── UserRepositoryAdapter.java
 └── config
      └── AppConfig.java
```

**Comment by Biotea92** [comment]
### 멀티 모듈 
`storage / api-user / api-admin / support` 모듈 구조에서는 onion architecture와 비슷하게 이용할 예정입니다.


- storage 
```
domain
  ├── user
  │   ├── entity
  │   │   └── User.java
  │   ├── service
  │   │   └── UserService.java
  │   └── repository
  │       └── UserRepository.java
  └── post
      ├── entity
      │   └── Post.java
      ├── service
      │   └── PostService.java
      └── repository
          └── PostRepository.java

```

- api-user, api-admin

```
├── application
│   ├── user
│   │   ├── usecase
│   │   │   └── RegisterUserUseCase.java
│   │   └── dto
│   │       └── UserDto.java
│   └── post
│       ├── usecase
│       │   └── GetPostUseCase.java
│       └── dto
│           └── PostDto.java
└── presentation
    ├── user
    │   ├── dto
    │   │   └── UserResponse.java
    │   ├── controller
    │   │   └── UserController.java
    │   └── exception
    │       ├── UserExceptionHandler.java
    │       └── UserNotFoundException.java
    └── post
        ├── dto
        │   └── PostResponse.java
        ├── controller
        │   └── PostController.java
        └── exception
            ├── PostExceptionHandler.java
            └── PostNotFoundException.java
```

- support
```
support
├── exception
│   ├── CustomException.java
│   └── ErrorDetails.java
└── utils
    ├── DateUtils.java
    └── StringUtils.java

```


- infrastructure(추가)

```
infrastructure
├── persistence
│   ├── user
│   │   └── UserJpaRepository.java
│   └── post
│       └── PostJpaRepository.java
├── config
│   ├── JpaConfig.java
│   └── SecurityConfig.java
└── external
    └── ExternalPaymentService.java
```

**Comment by f-lab-robert** [comment]
이 부분도 다시 학습해보시면 좋을 것 같습니다. 각 옵션의 장단점을 비교하는 것이 학습의 핵심이지, 단순 옵션을 나열하는 것은 학습이 아닐 뿐더러 선택의 기준이 될 수 없습니다.

**Comment by f-lab-robert** [comment]
결론 : 기본 멀티모듈 형태 + layer 형태
