### ISSUE TITLE
[Spring Security] 학습

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/travel-board#8]
**[Context]**
1. 개인 Repo 에 프로젝트 2개 생성

2. 인증 ( 로그인, 회원가입, ..[로그아웃]) 구현 
   - Session / Cookie & Local docker > Redis
   - JWT 를 이용한 Access & Refresh Token

**Comment by f-lab-robert** [comment]
시연 필요 !!!

**Comment by Biotea92** [comment]
## [Spring Security](https://docs.spring.io/spring-security/reference/index.html)

- 강력하고 사용자 정의가 가능한 인증 및 액세스 제어 프레임워크 
- Spring 기반 애플리케이션 보안을 위한 사실상의 표준
- Spring Security는 Java 애플리케이션에 인증과 권한 부여를 모두 제공하는 데 중점을 둔 프레임워크
- Spring Security의 진정한 힘은 사용자 정의 요구 사항을 충족하도록 얼마나 쉽게 확장할 수 있는지에 있습니다.

### 특징 
- 인증 및 권한 부여에 대한 포괄적이고 확장 가능한 지원
- 세션 고정, 클릭재킹, 크로스 사이트 요청 위조 등과 같은 공격으로부터 보호
- 서블릿 API 통합
- Spring Web MVC와의 선택적 통합

### 주요 기능 
- 모든 endpoint (`/error` endpoint 포함)에 대해 인증된 사용자가 필요
- 시작 시 생성된 비밀번호로 기본 사용자를 등록 (비밀번호는 콘솔에 기록, ex. 8e557245-73e2-4286-969a-ff57fe326336)
- BCrypt 및 기타 도구를 사용하여 비밀번호 저장소를 보호
- Form 기반 로그인 및 로그아웃 흐름 제공
- HTTP 기본 로그인 뿐만 아니라 폼 기반 로그인 인증
- 콘텐츠 협상(Content negotiation)을 제공. 웹 요청의 경우 로그인 페이지로 리디렉션. 서비스 요청의 경우 `401 Unauthorized` 응답을 반환.
- CSRF 공격 완화
- 세션 고정 공격을 완화합니다.
- HTTPS를 보장하기 위해 Strict-Transport-Security를 작성
- 스니핑 공격을 완화하기 위해 X-Content-Type-Options를 작성
- 인증된 리소스를 보호하는 Cache Control 헤더를 작성
- 클릭재킹을 완화하기 위해 X-Frame-Options 작성
- `HttpServletRequest`의 인증 방법과 통합
- 인증 성공 및 실패 이벤트를 발행

### Architecture

#### FilterChain
- 여러 필터를 연결하여 체인 형태로 구성하고, 각 HTTP 요청이 이 체인을 통과하면서 필요한 보안 처리를 수행합니다.

#### DelegatingFilterProxy
- Spring의 `ApplicationContext` 내에 정의된 필터 빈(Bean)을 서블릿 컨테이너의 필터로 등록하여 필터의 생명 주기를 Spring에서 관리할 수 있도록 합니다.
- 서블릿 컨테이너의 필터와 Spring 관리 필터 간의 다리 역할을 수행합니다.

#### FilterChainProxy
- 여러 보안 필터를 하나의 필터 체인으로 관리하며, 중앙에서 일괄적으로 보안 정책을 적용할 수 있도록 합니다.
- 각 요청마다 어떤 필터를 적용할지 결정하는 로직을 포함합니다.
- 보안 설정을 중앙에서 관리하여 유지 보수성을 높입니다.

#### SecurityFilterChain
- 요청에 따라 다른 보안 필터를 적용할 수 있도록 구성합니다.
- 특정 URL 패턴이나 HTTP 메소드 등에 따라 맞춤형 보안 설정을 적용합니다.
- 예를 들어, /admin/** 경로에는 관리자 권한이 필요한 필터를 적용하고, /user/** 경로에는 일반 사용자 권한 필터를 적용하는 식으로 설정할 수 있습니다.

### Authentication
##### SecurityContextHolder
- 현재 인증된 사용자의 세부 정보를 저장하며, 기본적으로 ThreadLocal을 사용하여 현재 스레드에 저장됩니다.
- 애플리케이션 전반에 걸쳐 인증 정보를 접근할 수 있게 합니다.
##### SecurityContext
- 현재 사용자의 인증 정보를 포함하는 컨텍스트입니다.
- Authentication 객체를 포함하여 인증된 사용자의 정보를 제공합니다.
##### Authentication
- 인증된 사용자를 나타내며, 자격 증명(credentials)과 권한(granted authorities)을 포함합니다.
- 사용자가 인증되었는지 여부를 나타내는 플래그도 포함됩니다.
##### GrantedAuthority
- 사용자에게 부여된 특정 권한을 나타냅니다.
- 예를 들어, ROLE_USER, ROLE_ADMIN 같은 역할을 나타낼 수 있습니다.
##### AuthenticationManager
- 인증 프로세스를 정의하는 핵심 인터페이스입니다.
- 주로 ProviderManager가 이를 구현하여 사용됩니다.
##### ProviderManager
- 여러 AuthenticationProvider를 사용하여 인증을 처리합니다.
- 각 AuthenticationProvider는 특정 유형의 인증을 처리할 수 있습니다.
##### AuthenticationProvider
- 특정 인증 로직을 구현하는 인터페이스입니다.
- 예를 들어, 사용자 이름과 비밀번호를 기반으로 인증하거나, OAuth 토큰을 사용하는 등의 다양한 인증 방식을 처리할 수 있습니다.
##### AuthenticationEntryPoint
- 클라이언트가 인증이 필요할 때 자격 증명을 요청하는 데 사용됩니다.
- 주로 HTTP 401 응답을 반환하여 클라이언트에게 인증이 필요함을 알립니다.
##### AbstractAuthenticationProcessingFilter
- 인증 요청을 처리하는 기본 필터입니다.
- 특정 URL 패턴에 매핑되어 인증 프로세스를 시작합니다.

### Authorization

##### GrantedAuthority
- 사용자에게 부여된 권한을 나타내는 인터페이스입니다.
- 주로 SimpleGrantedAuthority를 사용하여 문자열 형태로 권한을 표현합니다.
- 역할 기반 권한은 기본적으로 ROLE_ 접두사를 사용합니다.

##### AuthorizationManager
- 인가 결정을 내리는 중심적인 인터페이스로, 요청, 메소드, 메시지 등의 인가를 처리합니다.
- check 메소드는 인가 여부를 결정하며, verify 메소드는 인가 실패 시 예외를 발생시킵니다.

##### AccessDecisionManager 및 AccessDecisionVoter
- 이전 버전에서 사용되던 인가 관리 인터페이스들로, AuthorizationManager로 대체되었습니다.
- 투표 기반 인가 결정을 내리는 여러 구현체가 제공됩니다.

##### Role Hierarchy
- 역할 계층을 설정하여 상위 역할이 하위 역할을 포함하도록 구성할 수 있습니다.
- 예를 들어, ROLE_ADMIN은 ROLE_USER와 ROLE_GUEST를 포함할 수 있습니다.

##### 인가 흐름
1. 요청 가로채기 : 클라이언트의 요청이 들어오면 Spring Security가 이를 가로채고 `AuthorizationManager`를 통해 인가 결정을 내립니다.
2. 인가 결정 : `AuthorizationManager`는 `GrantedAuthority`를 검사하여 사용자가 필요한 권한을 가지고 있는지 확인합니다. `Role Hierarchy`가 설정된 경우, 상위 역할의 권한도 검사합니다.
3. 결과 : 인가가 성공하면 요청이 계속 처리되며, 인가가 실패하면 예외가 발생하여 접근이 거부됩니다.
